#!/bin/bash

# copied from https://github.com/philss/dotfiles

# Replace terms inside files under the same repository.
# Usage git replace "old_term" "new_term"

original=$1;
new_version=$2;

echo "$original -> $new_version"
echo

for file in `git-grep-files $original`; do
  echo "Replacing in $file"

  sed -i "s/$1/$2/g" $file;
done;

echo;
echo "Done";
