#!/bin/bash

# copied from https://github.com/philss/dotfiles

# Cleans all merged branches (relative to the branch you are). Recommended to run from master.
# Fetch all merged branches that are not the master branch, and not the current branch
echo 'Deleting all merged branches...'
merged=`git branch --merged | awk -F ' * ' '{print $2}' | grep -v -e 'master' | grep -v -e '*'`

for branch in $merged; do
  echo "Removing .. $branch"
  git branch -d $branch
done

echo 'Done!'

